name: Ping Streamlit App
on:
  schedule:
    - cron: '*/5 * * * *'  # Corrected cron syntax to run every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest  # Recommended to use ubuntu instead of windows
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -o /dev/null "https://pt-app-cyy7yhjaqecurde69nmgvh.streamlit.app/"
