name: Ping Streamlit App

on:
  schedule:
    - cron: '*/5 * * * *'  # This sets the workflow to run every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -o /dev/null "https://pt-app-cyy7yhjaqecurde69nmgvh.streamlit.app/"
